# Generated by Django 3.2.7 on 2021-11-07 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('e_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Caption', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=50)),
                ('post_excerpt', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('post_slug', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField()),
                ('post_imagename', models.CharField(max_length=50)),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.author')),
                ('post_tag', models.ManyToManyField(null=True, to='blog.Tag')),
            ],
        ),
    ]
